{
 "title": "App metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Env", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "web_page_gen_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "web_page_gen_time_count{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "crawler_pages_parsed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crawler_pages_parsed_total{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "web_pages_served",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "web_pages_served{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "crawler_page_parse_time_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crawler_page_parse_time_count{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "crawler_site_connection_time_count",
   "type": "graph",
   "description": "время затраченное ботом на подключение к веб-сайту и загрузку веб-страницы",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "crawler_site_connection_time_count{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  }
 ]
}